# apacheインストール
- name: Install httpd
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd

- name: install libselinux-python
  yum: name=libselinux-python state=installed

- name: run httpd
  service: name=httpd state=started enabled=yes

- name: virtualhost設定 CentOS7
  sudo: yes
  template: src=vhosts_2_4.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf owner=root group=root mode=0644
  notify:
    - restart httpd
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: virtualhost設定 CentOS6
  sudo: yes
  template: src=vhosts_2_2.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf owner=root group=root mode=0644
  notify:
    - restart httpd
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

